### ISSUE TITLE
Customer library

### ISSUE THREAD

**Issue by GongChen-Charlie** [JulianSchliessus/controlled6DoFMotion#1]
Hi julian,

I took a look at the description of the controlled6DoFMotion library, it's about coupling the 6Dof motion with OpenFOAM. I know that in OF, there is a sixDoFrigidbodymotion solver, which is to calculate the 6DoF motion with dynamic mesh. So I wonder if your library is to calculate the 6DoF motion with overset mesh?

**Comment by JulianSchliessus** [comment]
Hi,

with this class you can impose a controlled motion via a socket connection. This was useful in the case where I coupled some structural solver via preCICE with OpenFOAM, because in preCICE, à priori, you cannot couple the rotation motion of the background mesh.
So yes, the library calculates the 6DoF motion of the overset background mesh (but also of the individual sub-parts).
If you want to have a look at the full setup you may look [here](https://doi.org/10.18419/darus-2232).
